### ISSUE TITLE
Tips for DNS? 

### ISSUE THREAD

**Issue by bluk10** [cnorick/ha-auto-guest-login#28]
Apologies, I've tried to self help and read the documentation but I must be missing an insight somewhere.
My server is https://uniquename.duckdns.org:8123, local at https://192.168.1.17:8123. I can't seem to get it to work. Have confirmed the login user/dashboard I created works.

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
(node:83) ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language. Avoid relying on their current behavior and syntax as those might change in a future version of Node.js.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:83) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
HomeAssistant found on port 8123
Auto Guest Login at port 8675

**Comment by bluk10** [comment]
Resolved by accessing the local link for the qr code. Thanks for this add on.

**Comment by cnorick** [comment]
Hi! Did you click on "open web UI" from the addon page? Did that work?

**Comment by cnorick** [comment]
Just saw your other reply. So glad you got it working!
