### ISSUE TITLE
can't start auto-guest-login

### ISSUE THREAD

**Issue by MrThiemann** [cnorick/ha-auto-guest-login#3]
Hey, I need your help please.
after I have installed your script and want to run it, I see the "Start Page" for a short moment, but it's terminated again.
I get the following message.

Can you help me?

<img width="801" alt="Bildschirmfoto 2022-04-20 um 19 47 24" src="https://user-images.githubusercontent.com/54147030/164291845-04f26065-5e56-4e80-8a8f-cd47d8430d0d.png">

<img width="1051" alt="Bildschirmfoto 2022-04-20 um 19 49 45" src="https://user-images.githubusercontent.com/54147030/164291968-e9798dc8-e263-4f6a-8a4f-eab6706a2f33.png">

**Comment by cnorick** [comment]
Hi @MrThiemann, I see you closed the issue. Did you solve your issue?
