### ISSUE TITLE
Update to documentation

### ISSUE THREAD

**Issue by innovatorgit** [cnorick/ha-auto-guest-login#6]
For the environment variable documentation I recommend removing the trailing "/" after .local. It seems to cause issues.

- CLIENTID=http://homeassistant.local/

**Comment by cnorick** [comment]
The trailing "/" seems to work for me, so I wonder what the difference is? One thing that may be useful in the documentation is to give steps for how to get the clientId. We recently added a short description of the clientId at the bottom of the readme, but maybe it should include specific steps?

**Comment by cnorick** [comment]
I just updated the README to make that clearer. Let me know what you think.
