### ISSUE TITLE
Docker error exec /usr/local/bin/docker-entrypoint.sh: exec format error

### ISSUE THREAD

**Issue by dsharmapgatss** [cnorick/ha-auto-guest-login#8]
Hi,
I am trying to make it work with docker but I keep getting following error

exec /usr/local/bin/docker-entrypoint.sh: exec format error

**Comment by cnorick** [comment]
It kinda sounds like it might be a problem with docker. The best advice I can give is to maybe try reinstalling docker.

Otherwise, you could consider cloning the repo and running the code outside of the docker container. That requires just a little bit more setup though.

**Comment by dsharmapgatss** [comment]
Thank you for responding.

I was able to make it work on a PI device by by rebuilding docker image by changing Dockerfile to use buster image 
FROM node:16-buster-slim

**Comment by cnorick** [comment]
Great! Glad you got it working

**Comment by Stooovie** [comment]
> FROM node:16-buster-slim

Can you please elaborate for a noob? Where do I put this? Thanks!
